apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  tls:
    - hosts:
        - educk.io
  rules:
    - host: api.educk.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: entsoe-service
                port:
                  number: 3000

